spring.application.name=crm-application

# JPA / database defaults (can override per env)
spring.datasource.url=jdbc:postgresql://localhost:5432/deshkar
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto= update

# SMTP settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=user
spring.mail.password=pass
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
app.jwt.secret=ReplaceThisWithAStrongRandomSecretAtLeast32BytesLong!
app.jwt.expiration-ms=3600000

# CORS: allow your Angular dev server
app.cors.allowed-origins=http://localhost:4200

# Log file location
logging.file.name=crm-application/logs/application.log

# Log level for your app
logging.level.com.crm.deshkarStudio=DEBUG

# Log level for Spring framework (optional)
logging.level.org.springframework=WARN

# Log pattern (timestamp, level, logger, message)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Mail variables
app.mail.from=communication@deshkarstudio.in
app.mail.to=deshkarashay@gmail.com,deshkarprashant@gmail.com
app.mail.cc=itschinmayd@gmail.com

#springdoc.swagger-ui.path=/internal-docs-7f3k9x2m
#springdoc.api-docs.path=/internal-openapi-4p8q2n6z